version: '3.9'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: test
    volumes:
      - /home/root/data/postgresql
    networks:
      - mail-delivery-network

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - /home/root/data/backend
    environment:
      - KAFKA_SERVER=kafka-server:29092
      - DATABASE=postgresql
    networks:
      - mail-delivery-network
    depends_on:
      - kafka-server

  mail-delivery-service:
    container_name: mail-delivery-service
    build:
      context: mailSender
      dockerfile: Dockerfile
    ports:
      - "7500:7500"
    environment:
      - KAFKA_SERVER=kafka-server:29092
    networks:
      - mail-delivery-network
    depends_on:
      - kafka-server

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka-server:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss512K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka-server"
    networks:
      - mail-delivery-network

  zookeeper:
    image: docker.io/bitnami/zookeeper:3-debian-10
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - mail-delivery-network

  kafka-server:
    image: docker.io/bitnami/kafka:2-debian-10
    restart: "no"
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-server:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - mail-delivery-network
    depends_on:
      - zookeeper

networks:
  mail-delivery-network:
    driver: bridge
