
export enum ApplicationStatus {
    IN_PROCESS = 'IN_PROCESS',
    TESTINS = 'TESTING',
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED'
}