server:
  port: 7500
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: finf0094@gmail.com
    password: vsyjkiolrrbgcyue
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    protocol: smtp
    test-connection: false

kafka:
  username: todo-username
  password: todo-password
  servers: ${KAFKA_SERVER:localhost:9092}
  idempotence: true
  acks: all
  maxInFlightReq: 5
  group-id: hero-consumer
  auto-offset: earliest
  mechanism: PLAIN
  protocol: SASL_PLAINTEXT
  topics:
    test: send.email.test
    interview: send.email.interview