server:
  port: 3002

spring:
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.opxbumxpthagwcssmzia&password=gRoove48zxcvbnm!
    username: postgres
    password: 12341234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

kafka:
  servers: ${KAFKA_SERVER:localhost:9092}
  topics:
    test: send.email.test
    interview: send.email.interview

springdoc:
  swagger-ui:
    path: /api/docs

cors:
  allowed_origins: ${ALLOWED_ORIGIN:http://localhost:5173}